{% raw -%}

{{- if .Values.useLocalAssetVolume -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {% endraw %}{{ cookiecutter.app_slug }}-pvc{% raw %}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{ end }}

{%- endraw %}