{% raw -%}

apiVersion: v1
kind: Secret
metadata:
  name: {{ default .Chart.Name .Values.nameOverride }}-django-secrets
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretEnvironmentVariables }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  postgresql-host: {{ .Values.postgresql.postgresqlHost | default (printf "%s-postgresql" .Release.Name) | b64enc | quote  }}
  postgresql-user: {{ (default .Values.postgresql.postgresqlUsername .Values.global.postgresql.postgresqlUsername) | b64enc | quote }}
  postgresql-name: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  postgresql-password: {{ (default .Values.postgresql.postgresqlPassword .Values.global.postgresql.postgresqlPassword) | b64enc | quote }}
  postgresql-postgres-password: {{ (default .Values.postgresql.postgresqlPassword .Values.global.postgresql.postgresqlPassword) | b64enc | quote }}

{% endraw %}{% if cookiecutter.use_imagePullSecret == "yes" %}{% raw -%}
---

apiVersion: v1
kind: Secret
metadata:
  name: {% endraw %}"{{ cookiecutter.app_slug }}-robot-pull-secret"{% raw %}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
 .dockerconfigjson: {{ template {% endraw %}"{{ cookiecutter.app_slug }}.imagePullSecret"{% raw %} . }}

{% endraw %}{% endif -%}{% raw -%}

{%- endraw %}{% if cookiecutter.use_rabbitmq == "yes" %}{% raw -%}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ default .Chart.Name .Values.nameOverride }}-rabbitmq-custom
type: Opaque
data:
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote}}
  rabbitmq-host: {{ printf "%s-%s" .Release.Name "rabbitmq" | b64enc | quote }}
  rabbitmq-vhost: {{ .Values.rabbitmq.vhost | b64enc | quote }}
  rabbitmq-erlang-cookie : {{ .Values.rabbitmq.erlangSecret | b64enc | quote }}

{% endraw %}{% endif -%}{% raw -%}

{%- endraw %}
