{% raw -%}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-django-secrets
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretEnvironmentVariables }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  postgresql-host: {{ (default .Values.postgresql.postgresqlHost (printf "%s-postgresql" .Release.Name)) | b64enc | quote  }}
  postgresql-user: {{ (default .Values.postgresql.postgresqlUsername .Values.global.postgresql.postgresqlUsername) | b64enc | quote }}
  postgresql-name: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  postgresql-password: {{ (default .Values.postgresql.postgresqlPassword .Values.global.postgresql.postgresqlPassword) | b64enc | quote }}
  postgresql-postgres-password: {{ (default .Values.postgresql.postgresqlPassword .Values.global.postgresql.postgresqlPassword) | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: robot-pull-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
 .dockerconfigjson: {{ template "imagePullSecret" . }}

{%- endraw %}