{% raw -%}

apiVersion: v1
kind: Service
metadata:
  name: {{ include {% endraw %}"{{ cookiecutter.app_slug }}.fullname"{% raw %} . }}
  labels:
    {{- include {% endraw %}"{{ cookiecutter.app_slug }}.labels"{% raw %} . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include {% endraw %}"{{ cookiecutter.app_slug }}.selectorLabels"{% raw %} . | nindent 4 }}

{%- endraw %}