# Values for development environment
# Note: values in here should not overwrite those of ../values.yaml, they should only extend them!

global:
  postgresql:
    enabled: true
    postgresqlUsername: {{ cookiecutter.app_slug }}_dev
    existingSecret: {{ cookiecutter.app_slug }}-django-secrets

image:
  tag: latest
  pullPolicy: Always

environmentVariables:
  DJANGO_DEBUG: True
  DJANGO_ALLOWED_HOSTS: '*'

useLocalAssetVolume: true

assets:
  assetsMountPath: "/var/django"
  mediaPathPrefix: "/media/"
  staticPathPrefix: "/static/"

deploymentAnnotations: {}
deploymentLabels: {}

ingress:
  enabled: true
  enableLetsencrypt: false
  annotations: []
  annotationsBasicAuthExempt: []
  hosts:
    {{ cookiecutter.app_slug }}.dev.127.0.0.1.nip.io:
      path: /
      serviceName: {{ cookiecutter.app_slug }}
      servicePort: 8080
  tls: []
  basicAuthExempt: []
